### ISSUE TITLE
Error....

### ISSUE THREAD

**Issue by pulmuone** [venetasoft/Xamarin.CameraX#1]
Java.Lang.NoSuchMethodError: 'No virtual method getCamera()Landroidx/camera/core/Camera; in class Landroidx/camera/core/SurfaceRequest; or its super classes (declaration of 'androidx.camera.core.SurfaceRequest' appears in /data/app/~~8wdn_cXP7QbVNORKMGW8gg==/com.companyname.camerax-ezdSevPzCnIJz4d04WUb2Q==/base.apk)'

**Comment by limefrogyank** [comment]
You need to install a bunch more NuGet packages... see the csproj file.

**Comment by venetasoft** [comment]
?
Da: "Lee McPherson" ***@***.***
A: "venetasoft/Xamarin.CameraX" ***@***.***
Cc: "Subscribed" ***@***.***
Data: Fri, 28 May 2021 17:24:27 -0700
Oggetto: Re: [venetasoft/Xamarin.CameraX] Error.... (#1)


You need to install a bunch more NuGet packages... see the csproj file.
